### ISSUE TITLE
modes

### ISSUE THREAD

**Issue by Yusuf422** [ryant18/Vim-Quickstart#5]
I would consider changing the way you sort/define the sections, especially "modes."  Because "Basic Commands" are all normal mode commands, I would simply change the "modes" section into the "insert mode" section and have it sorted after the "normal/basic commands" section, or something similar.

**Comment by ryant18** [comment]
Fixed in 34ddafd016215ccee8f5ac37755b7a7c481177ed
The normal mode section was pretty redundant as it was just telling you to go to basic commands. So it made sense to just merge the commands under the normal mode header. The list of commands is unchanged, but some clarifying information was added to signify what is different about normal mode.
